[theme]
# Cor principal (botões, elementos ativos)
primaryColor = "#6366F1"

# Fundo global do app (bem escuro)
backgroundColor = "#050816"

# Fundo padrão de containers internos (cards/elementos)
secondaryBackgroundColor = "#0B1120"

# Cor padrão do texto
textColor = "#E5E7EB"

# Fonte
font = "sans"
