[theme]
# Cor principal (botões, foco, etc.)
primaryColor = "#10B981"              # verde tipo Tailwind emerald-500

# Fundo global da área principal
backgroundColor = "#F3F4F6"           # cinza bem claro (gray-100)

# Fundo padrão de containers internos (cards/tabelas)
secondaryBackgroundColor = "#FFFFFF"  # branco

# Cor padrão do texto
textColor = "#111827"                 # quase preto (gray-900)

# Fonte
font = "sans"
